#ifndef PIT_GAME_BATTLE_GLOBAL_PROPERTIES_H
#define PIT_GAME_BATTLE_GLOBAL_PROPERTIES_H

/* Values exposed to battle-AI opcodes 0x46 and 0x47. */
enum BattleGlobalProperty {
    BATTLE_GLOBAL_PROPERTY_00 = 0,
    BATTLE_GLOBAL_PROPERTY_01 = 1,
    BATTLE_GLOBAL_PROPERTY_02 = 2,
    BATTLE_GLOBAL_PROPERTY_03 = 3,
    BATTLE_GLOBAL_PROPERTY_04 = 4,
    BATTLE_GLOBAL_PROPERTY_SAVE_558 = 5,
    BATTLE_GLOBAL_PROPERTY_ACTIVE_PARTY_ACTOR = 6,
    BATTLE_GLOBAL_PROPERTY_ACTIVE_TARGET_ACTOR = 8,
    BATTLE_GLOBAL_PROPERTY_09 = 9,
    BATTLE_GLOBAL_PROPERTY_10 = 10,
    BATTLE_GLOBAL_PROPERTY_MAP_ID = 11,
    BATTLE_GLOBAL_PROPERTY_12 = 12,
    BATTLE_GLOBAL_PROPERTY_13 = 13,
    BATTLE_GLOBAL_PROPERTY_RUNTIME_FLAG_01 = 14,
    BATTLE_GLOBAL_PROPERTY_15 = 15,
    BATTLE_GLOBAL_PROPERTY_16 = 16,
    BATTLE_GLOBAL_PROPERTY_CONSTANT_NEGATIVE_ONE = 18,
    BATTLE_GLOBAL_PROPERTY_RUNTIME_FLAG_10 = 19,
    BATTLE_GLOBAL_PROPERTY_RUNTIME_FLAG_12 = 20,
    BATTLE_GLOBAL_PROPERTY_BACKGROUND_ID = 21,
    BATTLE_GLOBAL_PROPERTY_FADE_LEVEL = 22,
    BATTLE_GLOBAL_PROPERTY_FADE_COMPLETE = 23,
    BATTLE_GLOBAL_PROPERTY_24 = 24,
    BATTLE_GLOBAL_PROPERTY_INVERTED_MASK = 25,
    BATTLE_GLOBAL_PROPERTY_MASK = 26,
    BATTLE_GLOBAL_PROPERTY_27 = 27,
    BATTLE_GLOBAL_PROPERTY_RUNTIME_FLAG_17 = 28,
    BATTLE_GLOBAL_PROPERTY_RUNTIME_FLAG_02 = 29,
    BATTLE_GLOBAL_PROPERTY_RELOAD_BACKGROUND = 30,
    BATTLE_GLOBAL_PROPERTY_TOGGLE_BACKGROUND = 31,
    BATTLE_GLOBAL_PROPERTY_TOGGLE_FADE = 32,
    BATTLE_GLOBAL_PROPERTY_CONSTANT_ZERO = 33
};

/* Storage locations awaiting names from runtime observation. */
enum BattleGlobalPropertyOffset {
    BATTLE_GLOBAL_00_OFFSET = 0x18,
    BATTLE_GLOBAL_09_OFFSET = 0x20,
    BATTLE_GLOBAL_FADE_STEP_OFFSET = 0x24,
    BATTLE_GLOBAL_10_OFFSET = 0x26,
    BATTLE_GLOBAL_ACTIVE_PARTY_ACTOR_OFFSET = 0x38,
    BATTLE_GLOBAL_24_OFFSET = 0x3C,
    BATTLE_GLOBAL_16_OFFSET = 0x84,
    BATTLE_GLOBAL_15_OFFSET = 0x86,
    BATTLE_GLOBAL_01_OFFSET = 0x112,
    BATTLE_GLOBAL_03_OFFSET = 0x114,
    BATTLE_GLOBAL_04_OFFSET = 0x116,
    BATTLE_GLOBAL_02_OFFSET = 0x118,
    BATTLE_GLOBAL_MASK_OFFSET = 0x11C,
    BATTLE_GLOBAL_12_OFFSET = 0xCB78,
    BATTLE_GLOBAL_13_OFFSET = 0xCB7A,
    BATTLE_GLOBAL_27_OFFSET = 0xCB80,
    BATTLE_GLOBAL_FADE_LEVEL_OFFSET = 0xD390,
    BATTLE_GLOBAL_FADE_COUNTER_OFFSET = 0xD392,
    SAVE_GLOBAL_05_OFFSET = 0x558,
    SAVE_MAP_ID_OFFSET = 0x55A
};

#ifdef __cplusplus
extern "C" {
#endif

int BattleGlobalProperty_Get(int property);
void BattleGlobalProperty_Set(int property, int value);

#ifdef __cplusplus
}
#endif

#endif
