#ifndef PIT_GAME_LINKER_OVERLAY_IDS_H
#define PIT_GAME_LINKER_OVERLAY_IDS_H
#include <nitro.h>

/* Absolute values generated by DSD's linker script, not storage addresses.
 * Taking a symbol's address supplies the overlay ID to the loader. */
#ifdef __cplusplus
extern "C" {
#endif
extern u8 OVERLAY_10_ID[];
extern u8 OVERLAY_11_ID[];
extern u8 OVERLAY_12_ID[];
extern u8 OVERLAY_13_ID[];
extern u8 OVERLAY_14_ID[];
extern u8 OVERLAY_15_ID[];
extern u8 OVERLAY_16_ID[];
extern u8 OVERLAY_17_ID[];
extern u8 OVERLAY_18_ID[];
extern u8 OVERLAY_20_ID[];
extern u8 OVERLAY_21_ID[];
extern u8 OVERLAY_25_ID[];
extern u8 OVERLAY_26_ID[];
#ifdef __cplusplus
}
#endif
#endif
