#!/usr/bin/env python3
"""Report PiT battle-VM semantic and real-script coverage without ROM bytes."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path

import data_mod


ROOT = Path(__file__).resolve().parents[1]


def iter_commands(document: dict):
    if document.get("schema") == data_mod.BATTLE_SCRIPT_SCHEMA:
        for entry in document["entries"]:
            for segment in entry["segments"]:
                if segment["kind"] == "code":
                    yield from segment["commands"]
        return
    if document.get("schema") == data_mod.BATTLE_SCRIPT_SCHEMA_V1:
        for entry in document["entries"]:
            for script in entry["scripts"]:
                yield from script["commands"]


def opcode_number(value: object, names: dict[int, str]) -> int:
    reverse = {name: opcode for opcode, name in names.items()}
    if isinstance(value, str) and value in reverse:
        return reverse[value]
    if isinstance(value, str) and value.startswith("op_"):
        return int(value[3:], 16)
    return int(value)


def scan_scripts(scripts_root: Path, names: dict[int, str]) -> tuple[Counter, int, int]:
    usage: Counter[int] = Counter()
    entry_count = 0
    private_bytes = 0
    for path in sorted(scripts_root.glob("*.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        entry_count += len(document.get("entries", []))
        for command in iter_commands(document):
            usage[opcode_number(command["opcode"], names)] += 1
        if document.get("schema") == data_mod.BATTLE_SCRIPT_SCHEMA:
            private_bytes += sum(
                segment["size"]
                for entry in document["entries"]
                for segment in entry["segments"]
                if segment["kind"] == "private_data"
            )
    return usage, entry_count, private_bytes


def status_for(opcode: int, names: dict[int, str]) -> str:
    if opcode <= 0x32:
        return "reconstructed C"
    if opcode in names:
        return "static semantics"
    return "unknown"


def descriptor_summary(descriptor: int) -> str:
    count = descriptor & 0x1F
    result = "result + " if descriptor & 0x20 else ""
    modes = "typed args" if descriptor & 0x40 else "literal args"
    return f"{result}{count} {modes}"


def load_instance_config(version: str, name: str) -> dict:
    path = ROOT / "config" / version / f"{name}_vm.json"
    document = json.loads(path.read_text(encoding="utf-8"))
    if document.get("schema") != "pit-script-vm-descriptors-v1":
        raise ValueError(f"{path} has an unsupported schema")
    descriptors = [int(value, 0) for value in document["descriptors"]]
    document["descriptor_values"] = descriptors
    return document


def render_markdown(
    descriptors: tuple[int, ...],
    names: dict[int, str],
    usage: Counter[int],
    entry_count: int,
    private_bytes: int,
    field: dict,
    scene: dict,
) -> str:
    named_used = sum(opcode in names for opcode in usage)
    named_commands = sum(count for opcode, count in usage.items() if opcode in names)
    unresolved = sorted(
        ((count, opcode) for opcode, count in usage.items() if opcode not in names),
        reverse=True,
    )
    all_descriptor_sets = [
        field["descriptor_values"], list(descriptors), scene["descriptor_values"]
    ]
    common_prefix = 0
    for values in zip(*all_descriptor_sets):
        if len(set(values)) != 1:
            break
        common_prefix += 1
    shared_shapes = sum(
        len(set(values)) == 1 for values in zip(*all_descriptor_sets)
    )
    lines = [
        "# Script VM semantics",
        "",
        "This report is generated by `tools/report_battle_vm.py` from the checked-in",
        "descriptor table and the control-flow-disassembled battle scripts. It contains",
        "no original private data bytes.",
        "",
        "## Current coverage",
        "",
        f"- {len(descriptors)} descriptor entries (`0x000..0x{len(descriptors) - 1:03X}`)",
        f"- {entry_count} archive entries and {sum(usage.values()):,} reachable commands",
        f"- {len(usage)} opcodes occur in reachable code",
        f"- {named_used}/{len(usage)} used opcodes have semantic names",
        f"- {named_commands:,}/{sum(usage.values()):,} reachable commands have semantic names",
        f"- {private_bytes:,} non-code bytes stay private and are copied from the user's extraction",
        "",
        "`reconstructed C` means the generic VM implementation is represented in the",
        "decompilation. `static semantics` means the battle handler's effect is supported",
        "by its overlay-2 implementation and named callees, but its complete argument",
        "contract may still need call-site and runtime validation. `unknown` is deliberately",
        "left neutral.",
        "",
        "## Known VM instances",
        "",
        "The resident interpreter is shared, but its descriptor table, command handler,",
        "variable extension, and container grammar are selected by the loaded overlay.",
        "Static relocation scans find `VM_Run` clients in exactly overlays 0, 2, and 7.",
        "",
        "| Instance | Descriptor ABI | Command handler | `VM_Run` call sites | Proven role |",
        "|---|---|---|---|---|",
        "| Overlay 0 | 341 entries (`0x000..0x154`) at `0x020C00D0` | `func_ov000_020823f8` | `0x02088030` | Field/world events and actors |",
        "| Overlay 2 | 260 entries (`0x000..0x103`) at `0x020BF2C8` | dispatcher at `0x02079950` | 7 clients in the battle update cluster | Battle scenarios and enemy AI |",
        "| Overlay 7 | 210 entries (`0x000..0x0D1`) at `0x0208DCA4` | `func_ov007_02081730` | `0x02083FFC`, `0x02084508`, `0x02084530` | Scene/object scripts with 56 object slots |",
        "",
        "Overlay 0 exposes read-only field context through variables `0x3000..0x302A`.",
        "Overlay 7's matching `SceneScriptVM_ReadVariable` and",
        "`SceneScriptVM_WriteVariable` functions expose scene/task state at",
        "`0x7000..0x7009` and 32 shared words at",
        "`0x7010..0x702F`. Overlay 2 owns the named `battle.*` range. These meanings are",
        "instance-specific even though the resident variable switch recognizes all three",
        "namespace numbers.",
        "",
        "The European `FEvent/FEvData.dat` contains 1,914 outer entries arranged as 638",
        "room triplets. Part 1 is the localized 91-slot resource/dialogue container; parts",
        "0 and 2 are field-data members. Their first `u16` is both the first section offset",
        "and the complete `u16` pointer-table size. Pointer slots 0..8 select fixed typed",
        "sections; event-script slots begin at byte `0x12`.",
        "",
        "A complete static pass over the 778 nonempty field-data members classifies 18,651",
        "unique slot targets as valid VM entry points and 704 as deliberately opaque/private",
        "targets. The valid graphs contain 387,377 unique reachable commands using 289",
        "opcodes. `tools/field_event_mod.py` exports this classification and byte-identically",
        "rebuilds the source while enforcing fixed command boundaries and valid branch",
        "targets. Private targets and all nine not-yet-fully-typed data sections remain copied",
        "from the user's own extraction.",
        "",
        "The nine fixed pointer roles currently recovered from",
        "`func_ov000_020791e8` and their consumers are:",
        "",
        "| Slot | Parsed shape | Current role |",
        "|---:|---|---|",
        "| 0 | direct pointer | default event-entry selector table |",
        "| 1 | `u32 count` + 24-byte records | trigger/region records, expanded to 44-byte runtime objects |",
        "| 2 | `u32 count` + `u32` IDs | field resource definitions, expanded to 24-byte runtime entries |",
        "| 3 | `u32 count` + `u32` IDs | resource list, expanded to 20-byte runtime entries |",
        "| 4 | `u32 count` + `u32` IDs | second resource list, expanded to 20-byte runtime entries |",
        "| 5 | direct pointer | not yet typed |",
        "| 6 | count + payload | not yet typed |",
        "| 7 | count + 28-byte records | field entity descriptors |",
        "| 8 | direct pointer | not yet typed; frequently aliases the first script region |",
        "",
        "## Descriptor ABI coverage",
        "",
        f"The three tables have an identical `0x000..0x{common_prefix - 1:03X}` prefix:",
        "the 51 commands implemented by the resident interpreter. The first",
        "instance-specific descriptor is opcode `0x033`. Matching descriptor bytes beyond",
        "that boundary mean only the same encoded argument shape, not the same side effect.",
        f"Across the 210 indices present in every instance, {shared_shapes} happen to share",
        "the same shape.",
        "",
        "| Instance | Descriptor entries | Semantically named | Source |",
        "|---|---:|---:|---|",
        f"| Field/world | {len(field['descriptor_values'])} | {len(field['known_names'])} | `config/eur/field_vm.json` |",
        f"| Battle | {len(descriptors)} | {len(names)} | `config/eur/battle_ai_vm.json` |",
        f"| Scene/object | {len(scene['descriptor_values'])} | {len(scene['known_names'])} | `config/eur/scene_vm.json` |",
        "",
        "The field and scene tables are reproducibly extracted and checked against a private",
        "ROM with `tools/extract_script_vm_descriptors.py`; the committed JSON contains only",
        "the compact ABI metadata, never overlay bytes.",
        "",
        "## Recovered field control-flow family",
        "",
        "Overlay 0's first instance-specific family is statically complete enough to drive",
        "the field CFG exporter. Opcode `0x033` conditionally branches on the current VM",
        "owner subtype and `0x034` branches unconditionally. Opcodes `0x035..0x03B` manage",
        "indexed auxiliary script states. Opcodes `0x03C..0x03F` start, wait for, and skip",
        "inline scripts owned by a selected entity; `0x040..0x047` stop, pause, resume,",
        "query, or wait for selected/matching entity scripts. Opcode `0x048` starts an entry",
        "from the paired",
        "field context (the other DS screen/field instance).",
        "",
        "| Opcode | Name | Arguments | Behavior |",
        "|---:|---|---|---|",
    ]
    lines.extend(
        f"| `0x{opcode:03X}` | `{name}` | "
        f"{', '.join(field.get('opcode_semantics', {}).get(str(opcode), {}).get('arguments', [])) or descriptor_summary(field['descriptor_values'][opcode])} | "
        f"{field.get('opcode_semantics', {}).get(str(opcode), {}).get('effect', field.get('opcode_semantics', {}).get(str(opcode), {}).get('control_flow', 'named; detailed contract pending'))} |"
        for opcode, name in sorted(
            (int(raw_opcode, 0), name)
            for raw_opcode, name in field["known_names"].items()
            if int(raw_opcode, 0) >= 0x33
        )
    )
    lines.extend(
        [
            "",
            "## VM ABI",
            "",
            "Commands are streams of little-endian 16-bit words. The descriptor's low five",
            "bits hold the argument count, bit 5 adds a destination variable, and bit 6 adds",
            "an argument-mode mask. A set mode bit makes that argument a VM variable reference;",
            "a clear bit makes it a signed 16-bit literal. Fixed-point instructions combine",
            "two literal words when the corresponding first mode bit is clear.",
            "",
            "Relative control-flow operands are counted in halfwords from the end of the decoded",
            "command. `read_table` adds another two halfwords before its indexed 32-bit read.",
            "Schema v2 replaces every statically resolvable relative operand with a label and",
            "recomputes it when commands are inserted, removed, or resized.",
            "",
            "## Variable namespaces",
            "",
            "| Encoded range | Editable form | Meaning |",
            "|---:|---|---|",
            "| `0x1000..0x1FFF` | `state[n]` | Per-VM state words |",
            "| `0x2000..0x2FFF` | `save_flags_48[n]` | Save-data bit flags at `+0x48` |",
            "| `0x3000..0x3FFF` | `extension_3[n]` | Overlay-defined extension |",
            "| `0x4000..0x400A` | `battle.*` | Named battle owner/target/context values |",
            "| `0x4010..0x402F` | `battle.shared[n]` | 32 shared battle variables |",
            "| `0x5000..0x5FFF` | `save_words[n]` | Save-data words |",
            "| `0x6000..0x6FFF` | `save_bytes_d0[n]` | Save-data bytes at `+0xD0` |",
            "| `0x7000..0x7FFF` | `extension_7[n]` | Overlay-defined extension |",
            "| `0x8000..0x8FFF` | `context[n]` | VM-instance context words |",
            "| `0xA000..0xAFFF` | `state_24[n]` | State-relative words at `+0x24` |",
            "| `0xB000..0xBFFF` | `state_flags_64[n]` | State bit flags at `+0x64` |",
            "| `0xC000..0xCFFF` | `save_words_40[n]` | Save-data words at `+0x40` |",
            "| `0xD000..0xDFFF` | `save_flags_50[n]` | Save-data bit flags at `+0x50` |",
            "| `0xE000..0xFFFF` | `save_flags_1f0[n]` | Extended save-data bit flags at `+0x1F0` |",
            "",
            "## Highest-priority unresolved opcodes",
            "",
            "These are ordered by reachable use count, so resolving the top of this list gives",
            "the largest immediate improvement to editable script coverage.",
            "",
            "| Opcode | Uses |",
            "|---:|---:|",
        ]
    )
    lines.extend(f"| `0x{opcode:02X}` | {count:,} |" for count, opcode in unresolved)
    lines.extend(
        [
            "",
            "## Complete opcode table",
            "",
            "| Opcode | Name | Descriptor | Reachable uses | Evidence |",
            "|---:|---|---|---:|---|",
        ]
    )
    for opcode, descriptor in enumerate(descriptors):
        name = names.get(opcode, f"op_{opcode:03X}")
        lines.append(
            f"| `0x{opcode:03X}` | `{name}` | {descriptor_summary(descriptor)} "
            f"(`0x{descriptor:02X}`) | {usage[opcode]:,} | {status_for(opcode, names)} |"
        )
    lines.extend(
        [
            "",
            "## Completion criteria",
            "",
            "An opcode is only complete after its result, side effects, units, sentinel values,",
            "yield/retry behavior, and every argument are documented; representative scripts",
            "round-trip byte-identically; and at least one runtime trace confirms ambiguous",
            "state changes. Full event modding additionally requires completing overlay 0's",
            "`0x3000` extension, typing the scene structures behind overlay 7's recovered",
            "`0x7000` extension, and identifying every non-battle script archive.",
            "",
            "The descriptor schemas, FEvent pointer grammar, first field control-flow family,",
            "and lossless fixed-layout field exporter are now recovered. The remaining order is",
            "to name high-use field commands and type sections 0..8; finish the scene container",
            "and CFG exporter; validate ambiguous arguments with emulator traces; then enable",
            "relocation and merge field script/dialogue rebuilding into the normal data project.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default="eur")
    parser.add_argument(
        "--scripts-root", type=Path, default=ROOT / "data" / "eur" / "scripts"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "docs" / "research" / "SCRIPT_VM_SEMANTICS.md",
    )
    args = parser.parse_args()
    descriptors, names = data_mod.load_battle_vm_schema(args.version)
    field = load_instance_config(args.version, "field")
    scene = load_instance_config(args.version, "scene")
    usage, entry_count, private_bytes = scan_scripts(args.scripts_root, names)
    report = render_markdown(
        descriptors, names, usage, entry_count, private_bytes, field, scene
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8", newline="\n")
    print(f"Reachable commands: {sum(usage.values())}")
    print(f"Named used opcodes: {sum(opcode in names for opcode in usage)}/{len(usage)}")
    print(f"Output: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
