#!/usr/bin/env python3
"""Report PiT battle-VM semantic and real-script coverage without ROM bytes."""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path

import data_mod


ROOT = Path(__file__).resolve().parents[1]


def iter_commands(document: dict):
    if document.get("schema") == data_mod.BATTLE_SCRIPT_SCHEMA:
        for entry in document["entries"]:
            for segment in entry["segments"]:
                if segment["kind"] == "code":
                    yield from segment["commands"]
        return
    if document.get("schema") == data_mod.BATTLE_SCRIPT_SCHEMA_V1:
        for entry in document["entries"]:
            for script in entry["scripts"]:
                yield from script["commands"]


def opcode_number(value: object, names: dict[int, str]) -> int:
    reverse = {name: opcode for opcode, name in names.items()}
    if isinstance(value, str) and value in reverse:
        return reverse[value]
    if isinstance(value, str) and value.startswith("op_"):
        return int(value[3:], 16)
    return int(value)


def scan_scripts(scripts_root: Path, names: dict[int, str]) -> tuple[Counter, int, int]:
    usage: Counter[int] = Counter()
    entry_count = 0
    private_bytes = 0
    for path in sorted(scripts_root.glob("*.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        entry_count += len(document.get("entries", []))
        for command in iter_commands(document):
            usage[opcode_number(command["opcode"], names)] += 1
        if document.get("schema") == data_mod.BATTLE_SCRIPT_SCHEMA:
            private_bytes += sum(
                segment["size"]
                for entry in document["entries"]
                for segment in entry["segments"]
                if segment["kind"] == "private_data"
            )
    return usage, entry_count, private_bytes


def status_for(opcode: int, names: dict[int, str]) -> str:
    if opcode <= 0x32 and opcode not in range(0x05, 0x0A):
        return "reconstructed C"
    if opcode in names:
        return "static semantics"
    return "unknown"


def descriptor_summary(descriptor: int) -> str:
    count = descriptor & 0x1F
    result = "result + " if descriptor & 0x20 else ""
    modes = "typed args" if descriptor & 0x40 else "literal args"
    return f"{result}{count} {modes}"


def render_markdown(
    descriptors: tuple[int, ...],
    names: dict[int, str],
    usage: Counter[int],
    entry_count: int,
    private_bytes: int,
) -> str:
    named_used = sum(opcode in names for opcode in usage)
    named_commands = sum(count for opcode, count in usage.items() if opcode in names)
    unresolved = sorted(
        ((count, opcode) for opcode, count in usage.items() if opcode not in names),
        reverse=True,
    )
    lines = [
        "# Script VM semantics",
        "",
        "This report is generated by `tools/report_battle_vm.py` from the checked-in",
        "descriptor table and the control-flow-disassembled battle scripts. It contains",
        "no original private data bytes.",
        "",
        "## Current coverage",
        "",
        f"- {len(descriptors)} descriptor entries (`0x000..0x{len(descriptors) - 1:03X}`)",
        f"- {entry_count} archive entries and {sum(usage.values()):,} reachable commands",
        f"- {len(usage)} opcodes occur in reachable code",
        f"- {named_used}/{len(usage)} used opcodes have semantic names",
        f"- {named_commands:,}/{sum(usage.values()):,} reachable commands have semantic names",
        f"- {private_bytes:,} non-code bytes stay private and are copied from the user's extraction",
        "",
        "`reconstructed C` means the generic VM implementation is represented in the",
        "decompilation. `static semantics` means the battle handler's effect is supported",
        "by its overlay-2 implementation and named callees, but its complete argument",
        "contract may still need call-site and runtime validation. `unknown` is deliberately",
        "left neutral.",
        "",
        "## Known VM instances",
        "",
        "The resident interpreter is shared, but its descriptor table, command handler,",
        "variable extension, and container grammar are selected by the loaded overlay.",
        "Static relocation scans find `VM_Run` clients in exactly overlays 0, 2, and 7.",
        "",
        "| Instance | Descriptor ABI | Command handler | `VM_Run` call sites | Proven role |",
        "|---|---|---|---|---|",
        "| Overlay 0 | 341 entries (`0x000..0x154`) at `0x020C00D0` | `func_ov000_020823f8` | `0x02088030` | Field/world events and actors |",
        "| Overlay 2 | 260 entries (`0x000..0x103`) at `0x020BF2C8` | dispatcher at `0x02079950` | 7 clients in the battle update cluster | Battle scenarios and enemy AI |",
        "| Overlay 7 | 210 entries (`0x000..0x0D1`) at `0x0208DCA4` | `func_ov007_02081730` | `0x02083FFC`, `0x02084508`, `0x02084530` | Scene/object scripts with 56 object slots |",
        "",
        "Overlay 0 exposes read-only field context through variables `0x3000..0x302A`.",
        "Overlay 7's matching `SceneScriptVM_ReadVariable` and",
        "`SceneScriptVM_WriteVariable` functions expose scene/task state at",
        "`0x7000..0x7009` and 32 shared words at",
        "`0x7010..0x702F`. Overlay 2 owns the named `battle.*` range. These meanings are",
        "instance-specific even though the resident variable switch recognizes all three",
        "namespace numbers.",
        "",
        "`FEvent/FEvData.dat` is an outer room archive. Its localized room member contains",
        "91 slots (including dialogue), while the neighboring room members begin with",
        "16-bit pointer structures consumed by field logic. Those structures mix script",
        "entry points with non-code records; they therefore need typed loader recovery before",
        "the battle CFG decoder can be generalized safely.",
        "",
        "## VM ABI",
        "",
        "Commands are streams of little-endian 16-bit words. The descriptor's low five",
        "bits hold the argument count, bit 5 adds a destination variable, and bit 6 adds",
        "an argument-mode mask. A set mode bit makes that argument a VM variable reference;",
        "a clear bit makes it a signed 16-bit literal. Fixed-point instructions combine",
        "two literal words when the corresponding first mode bit is clear.",
        "",
        "Relative control-flow operands are counted in halfwords from the end of the decoded",
        "command. `read_table` adds another two halfwords before its indexed 32-bit read.",
        "Schema v2 replaces every statically resolvable relative operand with a label and",
        "recomputes it when commands are inserted, removed, or resized.",
        "",
        "## Variable namespaces",
        "",
        "| Encoded range | Editable form | Meaning |",
        "|---:|---|---|",
        "| `0x1000..0x1FFF` | `state[n]` | Per-VM state words |",
        "| `0x2000..0x2FFF` | `save_flags_48[n]` | Save-data bit flags at `+0x48` |",
        "| `0x3000..0x3FFF` | `extension_3[n]` | Overlay-defined extension |",
        "| `0x4000..0x400A` | `battle.*` | Named battle owner/target/context values |",
        "| `0x4010..0x402F` | `battle.shared[n]` | 32 shared battle variables |",
        "| `0x5000..0x5FFF` | `save_words[n]` | Save-data words |",
        "| `0x6000..0x6FFF` | `save_bytes_d0[n]` | Save-data bytes at `+0xD0` |",
        "| `0x7000..0x7FFF` | `extension_7[n]` | Overlay-defined extension |",
        "| `0x8000..0x8FFF` | `context[n]` | VM-instance context words |",
        "| `0xA000..0xAFFF` | `state_24[n]` | State-relative words at `+0x24` |",
        "| `0xB000..0xBFFF` | `state_flags_64[n]` | State bit flags at `+0x64` |",
        "| `0xC000..0xCFFF` | `save_words_40[n]` | Save-data words at `+0x40` |",
        "| `0xD000..0xDFFF` | `save_flags_50[n]` | Save-data bit flags at `+0x50` |",
        "| `0xE000..0xFFFF` | `save_flags_1f0[n]` | Extended save-data bit flags at `+0x1F0` |",
        "",
        "## Highest-priority unresolved opcodes",
        "",
        "These are ordered by reachable use count, so resolving the top of this list gives",
        "the largest immediate improvement to editable script coverage.",
        "",
        "| Opcode | Uses |",
        "|---:|---:|",
    ]
    lines.extend(f"| `0x{opcode:02X}` | {count:,} |" for count, opcode in unresolved)
    lines.extend(
        [
            "",
            "## Complete opcode table",
            "",
            "| Opcode | Name | Descriptor | Reachable uses | Evidence |",
            "|---:|---|---|---:|---|",
        ]
    )
    for opcode, descriptor in enumerate(descriptors):
        name = names.get(opcode, f"op_{opcode:03X}")
        lines.append(
            f"| `0x{opcode:03X}` | `{name}` | {descriptor_summary(descriptor)} "
            f"(`0x{descriptor:02X}`) | {usage[opcode]:,} | {status_for(opcode, names)} |"
        )
    lines.extend(
        [
            "",
            "## Completion criteria",
            "",
            "An opcode is only complete after its result, side effects, units, sentinel values,",
            "yield/retry behavior, and every argument are documented; representative scripts",
            "round-trip byte-identically; and at least one runtime trace confirms ambiguous",
            "state changes. Full event modding additionally requires completing overlay 0's",
            "`0x3000` extension, typing the scene structures behind overlay 7's recovered",
            "`0x7000` extension, and identifying every non-battle script archive.",
            "",
            "The implementation order is: recover the Overlay-0/7 descriptor schemas; type the",
            "`FEvent` room pointer consumers; identify every control-flow, spawn, wait, and",
            "terminal opcode; add lossless field/scene CFG exporters; then validate ambiguous",
            "arguments with emulator traces before assigning stable names. Only after all five",
            "steps should field scripts support size-changing edits.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default="eur")
    parser.add_argument(
        "--scripts-root", type=Path, default=ROOT / "data" / "eur" / "scripts"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "docs" / "research" / "SCRIPT_VM_SEMANTICS.md",
    )
    args = parser.parse_args()
    descriptors, names = data_mod.load_battle_vm_schema(args.version)
    usage, entry_count, private_bytes = scan_scripts(args.scripts_root, names)
    report = render_markdown(
        descriptors, names, usage, entry_count, private_bytes
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8", newline="\n")
    print(f"Reachable commands: {sum(usage.values())}")
    print(f"Named used opcodes: {sum(opcode in names for opcode in usage)}/{len(usage)}")
    print(f"Output: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
